### ISSUE TITLE
Link to about not found

### ISSUE THREAD

**Issue by flowsta** [medialab-prado/poblados-colonizacion-colonias-penitenciarias#3]
Me ha comentado Concha Catalán que en vuestro [index.html](https://medialab-prado.github.io/poblados-colonizacion-colonias-penitenciarias/) hay un [enlace](https://medialab-prado.github.io/poblados-colonizacion-colonias-penitenciarias/about) al pie de la página al equipo que no funciona

**Comment by LuisSevillano** [comment]
Si, es el link _ACERCA DEL PROYECTO. CRÉDITOS Y AGRADECIMIENTOS_. Puedes echarle un ojo @abe- ?

**Comment by abe-** [comment]
Sí, está por escribir. Trato de sacar hoy tiempo para ello.

**Comment by LuisSevillano** [comment]
Genial, acabo de comentar el link para evitar el error 404
